python train.py --gpu-id 0 \
                --loss Proxy_Anchor \
                --model resnet50_cgd \
                --embedding-size 1024 \
                --batch-size 120 \
                --lr 1e-4 \
                --dataset cub \
                --warm 5 \
                --bn-freeze 1 \
                --lr-decay-step 5 \
                --gd_config SMG \
                --experiment_name resnet50_cgd_1024